services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MOUNTAIN_ID: ${MOUNTAIN_ID}
        # Firebase Configuration
        NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID}
        NEXT_PUBLIC_YOUTUBE_API_KEY: ${NEXT_PUBLIC_YOUTUBE_API_KEY}
        # Youtube config
        YOUTUBE_CLIENT_ID: ${YOUTUBE_CLIENT_ID}
        YOUTUBE_CLIENT_SECRET: ${YOUTUBE_CLIENT_SECRET}
        YOUTUBE_REDIRECT_URI: ${YOUTUBE_REDIRECT_URI}
        YOUTUBE_REFRESH_TOKEN: ${YOUTUBE_REFRESH_TOKEN}
        GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
        # Kakaotalk OAuth
        NEXT_PUBLIC_KAKAO_CLIENT_ID: ${NEXT_PUBLIC_KAKAO_CLIENT_ID}
        NEXT_PUBLIC_KAKAO_CLIENT_SECRET: ${NEXT_PUBLIC_KAKAO_CLIENT_SECRET}
        NEXT_PUBLIC_KAKAO_OAUTH_ENABLED: ${NEXT_PUBLIC_KAKAO_OAUTH_ENABLED}
        # Application Configuration
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    restart: always
