-- work_tracking/schema.sql — the NORMATIVE schema for the work registry.
--
-- Read SCHEMA.md for the prose; this file is what actually enforces the rules.
-- Loaded into an IN-MEMORY SQLite database on every script run (node:sqlite).
-- No .db file is ever written to disk or committed — see
-- work-tracking-restructure-20260808.md §4.
--
-- Two jobs:
--   1. Index    — checkout queries it to find related items.
--   2. Validator — checkin DRY-RUN inserts work.json, rolls back, and only
--                  appends to registry.ndjson if every constraint passed.
--
-- STRICT requires SQLite >= 3.37. Node 25's node:sqlite ships 3.50+.
--
-- ---------------------------------------------------------------------------
-- CHANGING THIS SCHEMA — expected, but not symmetric
-- ---------------------------------------------------------------------------
-- The build re-validates the ENTIRE store on every run, so a tightened rule
-- retroactively invalidates rows written under the old one. Measured:
--
--   SAFE (old rows still load)        BREAKS HISTORY (old rows rejected)
--   - add a nullable column           - add NOT NULL with no DEFAULT
--   - add a column with a DEFAULT     - remove an enum value
--   - add an enum value               - tighten an existing CHECK
--   - add a CHECK on a NEW column     - add a CHECK to an existing column
--
-- ⚠️ That right-hand column is a heuristic, not the rule. The rule is: a change
-- breaks history iff some row already in the store violates it. So there is one
-- systematic exception, and it is worth knowing because the table above would
-- talk you out of the correct change:
--
--   A CHECK CONDITIONED ON A NEW ENUM VALUE CANNOT INVALIDATE HISTORY.
--
-- No historical row can hold a value that did not exist when it was written, so
-- `status <> 'deferred' OR note IS NOT NULL` is vacuously true for every row
-- already in the store. Measured against all 326 rows before it was added.
-- Such a rule therefore belongs HERE, where every script enforces it, rather
-- than in checkin.js, which a hand-edited registry.ndjson would bypass.
--
-- Additive changes: just make them. Edit this file, rebuild, done.
--
-- Restrictive changes: do NOT edit this file first. Either put the new rule in
-- checkin.js so it binds new writes only, or run a real migration and record it
-- as a `type: decision` row. Quietly tightening a CHECK turns every historical
-- row into a validation failure the next time anyone builds.
--
-- CHANGELOG
--   2026-08-09  +status 'deferred', and it MUST carry a note (owner). 'open' and
--               'abandoned' were both being used for parked work, which made
--               "what is open?" — the question the store exists to answer —
--               return items nobody could start. The note is what separates
--               parked-with-a-condition from quietly forgotten.
--   2026-08-09  +type 'question' (additive) — BACKLOG.md's open questions are
--               "not tasks until answered"; filing them as tasks misreports them.
--   2026-08-08  Initial schema.

CREATE TABLE records (
  -- identity ---------------------------------------------------------------
  id         TEXT    NOT NULL CHECK (id GLOB 'R-[0-9][0-9][0-9][0-9]'),
  rev        INTEGER NOT NULL CHECK (rev >= 1),
  ts         TEXT    NOT NULL CHECK (ts GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),

  -- classification ---------------------------------------------------------
  -- 'question' = an owner decision not yet answered. BACKLOG.md's own heading says
  -- these are "not tasks until answered", so filing one as a task misrepresents it.
  type       TEXT    NOT NULL CHECK (type   IN ('task','decision','bug','change','question')),
  -- 'deferred' = we still want it, but something must change first; the note says
  -- what. The test against 'abandoned' is whether you can name the condition that
  -- would restart it. If you can, it is deferred; if not, it was decided against.
  status     TEXT    NOT NULL CHECK (status IN ('open','in-progress','done',
                                                'abandoned','deferred')),
  outcome    TEXT             CHECK (outcome IS NULL OR
                                     outcome IN ('adopted','rejected','superseded')),

  -- content ----------------------------------------------------------------
  title      TEXT    NOT NULL CHECK (length(trim(title)) > 0),
  plan       TEXT,                      -- backlink to a PROJECT_PLAN section, e.g. '§10u'
  detail_ref TEXT,                      -- 'records/R-0142.md' — prose lives OUTSIDE the row
  note       TEXT,                      -- why THIS revision exists

  -- relationships ----------------------------------------------------------
  -- supersedes: JSON array of ids this row REPLACES (those items are dead).
  supersedes TEXT             CHECK (supersedes IS NULL OR
                                     (json_valid(supersedes) AND
                                      json_type(supersedes) = 'array')),
  -- split_from: the ONE parent this was broken out of (that item stays ALIVE).
  -- Scalar, not an array. Only the child stores the pointer; children are derived.
  split_from TEXT             CHECK (split_from IS NULL OR
                                     split_from GLOB 'R-[0-9][0-9][0-9][0-9]'),

  -- provenance -------------------------------------------------------------
  files      TEXT             CHECK (files IS NULL OR
                                     (json_valid(files) AND json_type(files) = 'array')),
  source_ref TEXT,                      -- 'BACKLOG.md#B1@4484234' — commit-pinned

  -- A deferred item must say WHY it is parked, on every revision that is deferred
  -- rather than only on the one that parked it. `registry.md` renders current rows,
  -- so a reason living only on the transition revision would show as a blank in the
  -- one view people actually read. Without this, 'deferred' becomes the bucket
  -- things go into to be quietly forgotten — which is the failure BACKLOG.md named:
  -- "a finding that lives only inside the story of the day it was found is one
  -- nobody schedules."
  CONSTRAINT deferred_needs_note CHECK (status <> 'deferred' OR
                                        (note IS NOT NULL AND length(trim(note)) > 0)),

  PRIMARY KEY (id, rev)
) STRICT;

-- A record is never edited; an update APPENDS a row with the next rev.
-- The PK above is therefore also the collision detector: two sessions that both
-- take R-0142 at rev 2 and both write rev 3 fail here rather than silently
-- producing two rows that each claim to be current.

CREATE INDEX idx_records_status ON records (status);
CREATE INDEX idx_records_type   ON records (type);
CREATE INDEX idx_records_plan   ON records (plan);
CREATE INDEX idx_records_parent ON records (split_from);

-- Derived staleness. `stale` is NEVER stored — writing it would mean editing an
-- existing line, which breaks every merge strategy tested (§4.3). It is computed.
CREATE VIEW records_with_stale AS
SELECT
  r.*,
  CASE WHEN r.rev = (SELECT MAX(rev) FROM records WHERE id = r.id)
       THEN 0 ELSE 1 END AS stale
FROM records r;

-- The current state of every item: one row per id, highest rev wins.
-- This is what checkout reads and what build.js renders into registry.md.
CREATE VIEW current_records AS
SELECT * FROM records r
WHERE r.rev = (SELECT MAX(rev) FROM records WHERE id = r.id);

-- Roll-up for a parent's children, for the hierarchy view in registry.md.
CREATE VIEW children_progress AS
SELECT
  p.id                                                   AS parent_id,
  COUNT(c.id)                                            AS children,
  SUM(CASE WHEN c.status = 'done' THEN 1 ELSE 0 END)     AS children_done
FROM current_records p
JOIN current_records c ON c.split_from = p.id
GROUP BY p.id;

-- NOT enforceable here, and therefore the job of checkin.js:
--   * split_from / supersedes must point at ids that EXIST and are present in
--     work.json. A SQL foreign key cannot express it: the PK is (id, rev) and
--     the reference is to id alone.
--   * A revision whose only differences are ts and rev MUST carry a note, or
--     checkin drops it as unmodified and the parent's timeline goes silent at
--     the moment it was decomposed.
