/**
 * Generates a TypeScript module from the single source-of-truth mountain config
 * so the deployed function can resolve `adminEmail` (the 동참 notification
 * recipient) without reaching outside its own package at runtime.
 *
 * Source of truth: config/mountains/mountains.json — edit there, not here.
 * Output (git-ignored): functions/src/mountains.generated.ts
 */
const fs = require('fs');
const path = require('path');

const SRC = path.resolve(__dirname, '../../config/mountains/mountains.json');
const DEST = path.resolve(__dirname, '../src/mountains.generated.ts');

if (!fs.existsSync(SRC)) {
  throw new Error(`Mountain config not found at ${SRC}`);
}

const json = fs.readFileSync(SRC, 'utf8');
const banner =
  '// AUTO-GENERATED by scripts/sync-config.js — do not edit.\n' +
  '// Source of truth: config/mountains/mountains.json\n';
fs.writeFileSync(DEST, `${banner}const mountains = ${json} as const;\nexport default mountains;\n`);
console.log(`[sync-config] ${SRC} -> ${DEST}`);
